Image placement policy module and its info module
nutanix/nutanix.ansible pull request #214
Opened 2022-06-16 08:35 UTC by bhati-pradeep

New modules:
- ntnx_image_placement_policy
- ntnx_image_placement_policies_info

2022-06-16 08:39 UTC, bhati-pradeep commented
/ok-to-test

2022-06-16 08:48 UTC, bhati-pradeep commented
/ok-to-test

2022-06-22 12:49 UTC, Gevorg-Khachatryan-97 approved these changes

2022-06-23 07:02 UTC, bhati-pradeep commented
/ok-to-test

2022-06-23 07:21 UTC, bhati-pradeep commented
/ok-to-test

2022-06-29 08:34 UTC, premkarat requested changes

2022-06-29 08:34 UTC, premkarat commented on README.md
> +| ntnx_image_placement_policy | Create, update or delete a image placement policy. |
can you order them in ascending name order

2022-06-29 08:34 UTC, premkarat commented on plugins/modules/ntnx_image_placement_policies_info.py
> +def get_particular_policies(module, result):
use word specific instead of particular

2022-06-29 08:34 UTC, premkarat commented on plugins/modules/ntnx_image_placement_policies_info.py
> +def get_particular_policies(module, result):
should it be get_all_policies()

2022-06-30 10:36 UTC, merged