Clusters, vlans, tm clusters , filters
nutanix/nutanix.ansible pull request #327
Opened 2023-02-08 15:47 UTC by Gevorg-Khachatryan-97

2023-02-12 14:12 UTC, bhati-pradeep requested changes

2023-02-12 14:12 UTC, bhati-pradeep commented on plugins/module_utils/ndb/snapshots.py
> +        if query_params.get("all"):
Also we have filters_map() method to convert "_" to "-", please do conversion before doing _build_query_params()

2023-02-12 14:12 UTC, bhati-pradeep commented on plugins/module_utils/ndb/time_machines.py
> +            "cluster": self._build_spec_cluster,
please create seperate builder called get_spec_for_data_access_management() and update _build_spec_methods in that and call get_spec(). As TimeMachine is creating spec for different purposes in different modules like databases

2023-02-12 14:12 UTC, bhati-pradeep commented on plugins/module_utils/ndb/time_machines.py
> +            "cluster": self._build_spec_cluster,
check builders (get_spec* methods) of  DbServerVM class for way to seperate builders as per the purpose

2023-02-12 14:12 UTC, bhati-pradeep commented on plugins/module_utils/ndb/time_machines.py
> +    def get_default_data_access_spec(self, override_spec=None):
get_default_data_access_spec can be called get_default_data_access_management_spec for more relevance

2023-02-12 14:12 UTC, bhati-pradeep commented on plugins/module_utils/ndb/time_machines.py
> +    def get_data_access_spec(self, old_spec=None):
assign build_spec_methods here with builders for DAM before as per required builders of data access management spec

2023-02-12 14:12 UTC, bhati-pradeep commented on plugins/module_utils/ndb/vlans.py
> +    def get_spec(self, old_spec=None, params=None):
Check update get_spec(). It has **kwargs which can be used to switch between builders for Vlans and strecthed VLans.

2023-02-12 14:12 UTC, bhati-pradeep commented on plugins/module_utils/ndb/vlans.py
> +    def get_spec(self, old_spec=None, params=None):
Or we can have seperate class for Vlans and StretchedVlans(Vlans).

2023-02-12 14:12 UTC, bhati-pradeep commented on plugins/module_utils/ndb/vlans.py
> +            old_property = self._get_property_by_name(
purpose of old_property ?

2023-02-12 14:12 UTC, bhati-pradeep commented on plugins/module_utils/ndb/vlans.py
> +        payload["type"] = "Static"
Is it the case everytime ?

2023-02-14 09:02 UTC, Gevorg-Khachatryan-97 commented on plugins/module_utils/ndb/clusters.py
> +    def delete(
here we are deleting cluster object from NDB, so it's not required

2023-02-14 09:17 UTC, Gevorg-Khachatryan-97 commented on plugins/module_utils/ndb/clusters.py
> +        else:
if dsip or dbserver is not given then prism vlan is use for all 3

2023-02-14 14:23 UTC, bhati-pradeep requested changes
@alaa-bish Can you please address test review

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_clusters/tasks/main.yml
> +        - import_tasks: "register_cluster.yml"
Seems we are doing CRUD tests here. Please change the naming

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_clusters/tasks/register_cluster.yml
> +- name: Register Cluster with prisim_vlan
prism_vlan

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_clusters/tasks/register_cluster.yml
> +      - result.response.name == "newname"
check if uuid is coming in response.

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_clusters/tasks/register_cluster.yml
> +- name: List all era clusters
use NDB everywhere

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_clusters/tasks/register_cluster.yml
> +    msg: Start testing ntnx_ndb_clusters
Add test case to check the spec created using check_mode. This will help us to identify if correct spec is being sent to server

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_time_machines_with_multi_clusters/tasks/data_access_management_and_snapshots.yml
> +      - out.tm_uuid is defined
@Gevorg-Khachatryan-97, output has been changed to time_machine_uuid right ? @alaa-bish  please check this tests

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_time_machines_with_multi_clusters/tasks/data_access_management_and_snapshots.yml
> +      - result.cluster_uuid is defined
Please check the cluster_uuid correctness as well here. For example, - result.cluster_uuid == cluster.cluster2.uuid

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_time_machines_with_multi_clusters/tasks/data_access_management_and_snapshots.yml
> +- name: delete time maschine
There should be assertions here to check if response is success or failures. In this file, I cannot find any tests for delete with assertions.

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_vlans/tasks/create_vlans.yml
> +- name: create Dhcp ndb vlan
Please test spec created using check_mode as well. This will identify any regression in first step itself without any calls to server.

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_vlans/tasks/create_vlans.yml
> +      uuid: "{{cluster.uuid}}"
vars file have changed. use cluster.cluster1.uuid

2023-02-14 14:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_ndb_vlans/tasks/create_vlans.yml
> +
Please test the response status if delete goes successfully or not

2023-02-17 10:25 UTC, bhati-pradeep requested changes

2023-02-17 10:25 UTC, bhati-pradeep commented on plugins/modules/ntnx_ndb_profiles_info.py
> +        # or module.params.get("profile_type")
Formatting

2023-02-17 10:25 UTC, bhati-pradeep commented on plugins/modules/ntnx_ndb_snapshots_info.py
> +                # "database-node",
Remove comments

2023-02-17 10:25 UTC, bhati-pradeep commented on plugins/modules/ntnx_ndb_stretched_vlans.py
> +            msg="Failed generating update stretched stretched vlan  spec", **result
Correct error message

2023-02-17 15:57 UTC, bhati-pradeep approved these changes
LGTM

2023-02-17 16:30 UTC, abhimutant approved these changes
LGTM

2023-02-17 16:39 UTC, merged