Adding ansible lint fixes for tests
nutanix/nutanix.ansible pull request #504
Opened 2024-09-25 09:39 UTC by george-ghawali

2024-10-08 08:32 UTC, bhati-pradeep requested changes

2024-10-08 08:32 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_foundation/tasks/negative_scenarios.yml
> +    success_msg: "Succes: returned response as expected"
success ?

2025-04-23 09:10 UTC, abhinavbansal29 commented on plugins/module_utils/v3/entity.py
> +            if info.get("msg"):
Please test this once.

2025-04-23 09:12 UTC, abhinavbansal29 commented on plugins/module_utils/v3/prism/user_groups.py
> +        if config[0:3] == "ou=":
If possible can you please explain why we are doing this?

2025-04-23 09:13 UTC, abhinavbansal29 commented on plugins/module_utils/v3/prism/vms.py
> +                disk.setdefault("data_source_reference", {})["uuid"] = uuid
Why are we doing this?

2025-04-23 09:30 UTC, abhinavbansal29 commented on tests/integration/targets/ntnx_karbon_registries/tasks/negative_scenarios.yml
> +    url: "{{url}}"
Why did you remove the spaces in url?

2025-04-23 09:30 UTC, abhinavbansal29 commented on tests/integration/targets/ntnx_karbon_registries/tasks/negative_scenarios.yml
> +    url: "{{url}}"
```suggestion
    url: "{{ url }}"
```

2025-04-23 09:34 UTC, abhinavbansal29 commented on tests/integration/targets/ntnx_karbon_registries/tasks/negative_scenarios.yml
>      success_msg: "Pass: Returned as expected "
Please change name of tests/integration/targets/ntnx_ndb_vlans/tasks/negative_scenarios.yml in main.yml as well

2025-04-23 09:35 UTC, abhinavbansal29 commented on tests/integration/targets/nutanix_vms/tasks/negative_scenarios.yml
>      fail_msg: " Fail deleting VM with missing uuid "
Please change name of tests/integration/targets/nutanix_vms/tasks/negative_vm_update.yml in main.yml

2025-05-19 06:11 UTC, closed without merging