Test Integration Fixes: Enhancing Stability
nutanix/nutanix.ansible pull request #510
Opened 2024-10-03 13:00 UTC by george-ghawali

- Adding some delay after creating static route since it needs some time to be active
- Add minor fix in service groups test that assert empty list

2024-10-08 05:23 UTC, bhati-pradeep requested changes

2024-10-08 05:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_static_routes/tasks/create.yml
> +- name: Wait 1 minute for static routes to be created
```suggestion
- name: Wait 1 minute for static routes to become active 
```

2024-10-08 05:23 UTC, bhati-pradeep commented on tests/integration/targets/ntnx_static_routes/tasks/create.yml
> +- name: Wait 1 minute for static routes to be created
Update this everywhere

2024-12-09 12:26 UTC, abhinavbansal29 requested changes

2024-12-09 12:26 UTC, abhinavbansal29 commented on tests/integration/targets/ntnx_static_routes/tasks/create.yml
> +    success_msg: "Succes: static routes updated successfully"
```suggestion
    success_msg: "Success: static routes updated successfully"
```

2024-12-09 12:26 UTC, abhinavbansal29 commented on tests/integration/targets/ntnx_static_routes/tasks/create.yml
> +    success_msg: "Succes"
```suggestion
    success_msg: "Success"
```

2024-12-11 13:04 UTC, george-ghawali commented on tests/integration/targets/ntnx_static_routes/tasks/create.yml
> +    success_msg: "Succes"
fixed in different PR

2025-05-19 06:13 UTC, closed without merging