Adding imprv where user can group VMs by project name
nutanix/nutanix.ansible pull request #511
Opened 2024-10-07 08:37 UTC by george-ghawali

2024-10-07 12:09 UTC, bhati-pradeep requested changes

2024-10-07 12:09 UTC, bhati-pradeep commented on plugins/inventory/ntnx_prism_vm_inventory.py
> +                    "ntnx_project",
Lets have attribute called - `project_reference`

2024-10-07 12:09 UTC, bhati-pradeep commented on plugins/inventory/ntnx_prism_vm_inventory.py
> +                    "ntnx_project",
Assign directly this `entity.get("metadata", {}).get("project_reference", {})`

2024-10-08 09:14 UTC, bhati-pradeep approved these changes

2024-10-08 09:23 UTC, bhati-pradeep approved these changes

2024-10-08 09:39 UTC, george-ghawali commented
Adding new variable project_reference in host vars
![imprvissue#500](https://github.com/user-attachments/assets/e96425b9-3ea6-4503-9191-d6c76bbc4e00)

2024-10-08 09:41 UTC, merged