Added Error message for dynamic inventory if wrong credentials are passed
nutanix/nutanix.ansible pull request #512
Opened 2024-10-07 11:08 UTC by abhinavbansal29

Issue: https://github.com/nutanix/nutanix.ansible/issues/421

2024-10-08 10:04 UTC, bhati-pradeep requested changes

2024-10-08 10:04 UTC, bhati-pradeep commented on plugins/module_utils/entity.py
> +                    error=resp["message_list"],
```suggestion
                    error=resp.get("message_list"),
```

2025-04-15 09:45 UTC, bhati-pradeep commented
Hi @abhinavbansal29 Please merge main branch once. Then we can run checks.

2025-05-06 08:29 UTC, abhinavbansal29 commented
Closing this PR as this is old PR, created new one in place. This has a lot of conflicts against main.

2025-05-06 08:29 UTC, closed without merging